/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseConfirmDialog: typeof import('./src/components/base/BaseConfirmDialog.vue')['default']
    BaseDialog: typeof import('./src/components/base/BaseDialog.vue')['default']
    BaseDrawer: typeof import('./src/components/base/BaseDrawer.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseOrderBy: typeof import('./src/components/base/BaseOrderBy.vue')['default']
    BaseOverlay: typeof import('./src/components/base/BaseOverlay.vue')['default']
    BasePagination: typeof import('./src/components/base/BasePagination.vue')['default']
    BaseSelect: typeof import('./src/components/base/BaseSelect.vue')['default']
    BaseSpinner: typeof import('./src/components/base/BaseSpinner.vue')['default']
    BaseTabs: typeof import('./src/components/base/BaseTabs.vue')['default']
    Burger: typeof import('./src/components/header/Burger.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
