FROM node:20.19-alpine AS build

WORKDIR /app

ARG VITE_API_URL
ARG VITE_API_PREFIX
ARG VITE_AUTH_GOOGLE_CLIENT_ID

ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_API_PREFIX=${VITE_API_PREFIX}
ENV VITE_AUTH_GOOGLE_CLIENT_ID=${VITE_AUTH_GOOGLE_CLIENT_ID}

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine

RUN apk add --no-cache openssl

ARG APP_DOMAIN

ENV APP_DOMAIN=${APP_DOMAIN}

COPY --from=build /app/nginx/default.conf.template /etc/nginx/templates/
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
