FROM node:20.19-alpine AS build

WORKDIR /app

ARG VITE_API_URL
ARG VITE_API_PREFIX
ARG VITE_AUTH_GOOGLE_CLIENT_ID

ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_API_PREFIX=${VITE_API_PREFIX}
ENV VITE_AUTH_GOOGLE_CLIENT_ID=${VITE_AUTH_GOOGLE_CLIENT_ID}

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
