services:
  frontend:
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_API_PREFIX: ${VITE_API_PREFIX}
        VITE_AUTH_GOOGLE_CLIENT_ID: ${VITE_AUTH_GOOGLE_CLIENT_ID}
        APP_DOMAIN: ${APP_DOMAIN}
    networks:
      - app-network
    volumes:
      - ./frontend/nginx/certbot/conf:/etc/letsencrypt
      - ./frontend/nginx/certbot/www:/var/www/certbot
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "80"]
      interval: 5s
      timeout: 2s
      retries: 10
  backend:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      args:
        DATABASE_URL: ${DATABASE_URL}
    env_file:
      - ./backend/.env.production
    networks:
      - db-network
      - app-network
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: "${DB}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB}"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      db-network:

  certbot:
    image: certbot/certbot
    depends_on:
      frontend:
        condition: service_healthy
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
    volumes:
      - ./frontend/nginx/certbot/conf:/etc/letsencrypt
      - ./frontend/nginx/certbot/www:/var/www/certbot
      - ./frontend/nginx/certbot-entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

volumes:
  postgres_data:

networks:
  db-network:
  app-network:
