FROM node:22-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/package.json .
COPY --from=builder /app/package-lock.json .
COPY ./prisma.config.ts /app/prisma.config.ts

RUN npm ci --omit=dev
RUN npx prisma generate

CMD ["sh", "-c", "npx prisma migrate deploy && node dist/src/server.js"]