export const DB_ERROR_CODES = {
  UNIQUE_CONSTRAINT: "DB_UNIQUE_CONSTRAINT",
  RECORD_NOT_FOUND: "DB_RECORD_NOT_FOUND",
  FOREIGN_KEY: "DB_FOREIGN_KEY",
} as const;

export type DbErrorCode = (typeof DB_ERROR_CODES)[keyof typeof DB_ERROR_CODES];

export const PRISMA_ERROR_CODES = {
  UNIQUE_CONSTRAINT: "P2002",
  RECORD_NOT_FOUND: "P2025",
  FOREIGN_KEY: "P2003",
} as const;

export type PrismaErrorCode =
  (typeof PRISMA_ERROR_CODES)[keyof typeof PRISMA_ERROR_CODES];

export const PRISMA_TO_DB_ERROR_MAP: Record<PrismaErrorCode, DbErrorCode> = {
  [PRISMA_ERROR_CODES.UNIQUE_CONSTRAINT]: DB_ERROR_CODES.UNIQUE_CONSTRAINT,
  [PRISMA_ERROR_CODES.RECORD_NOT_FOUND]: DB_ERROR_CODES.RECORD_NOT_FOUND,
  [PRISMA_ERROR_CODES.FOREIGN_KEY]: DB_ERROR_CODES.FOREIGN_KEY,
};
