import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import {
  faGauge,
  faReceipt,
  faChartLine,
  faWallet,
  faRightToBracket,
  faRightFromBracket,
  faUserPlus,
  faPaperPlane,
  faKey,
  faLock,
  faSort,
  faArrowUp,
  faArrowDown,
  faPen,
  faTrash,
  faPlus,
  faXmark,
  faCheck,
  faTimes,
  faSpinner,
  faFolder,
  faTag,
  faCreditCard,
  faMoneyBill,
  faSliders,
  faRotateLeft,
  faChevronDown,
  faInbox,
  faBolt,
  faChartBar,
  faPlusCircle,
  faLayerGroup,
  faCheckCircle,
  faFileExport,
  faFileImport,
  faFileArrowUp,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faGauge,
  faReceipt,
  faChartLine,
  faWallet,
  faRightToBracket,
  faRightFromBracket,
  faUserPlus,
  faPaperPlane,
  faKey,
  faLock,
  faSort,
  faArrowUp,
  faArrowDown,
  faPen,
  faTrash,
  faPlus,
  faXmark,
  faCheck,
  faTimes,
  faSpinner,
  faReceipt,
  faFolder,
  faTag,
  faCreditCard,
  faMoneyBill,
  faSliders,
  faRotateLeft,
  faChevronDown,
  faInbox,
  faBolt,
  faChartBar,
  faPlusCircle,
  faLayerGroup,
  faCheckCircle,
  faFileExport,
  faFileImport,
  faFileArrowUp,
);

export { FontAwesomeIcon };
